pipeline {
    agent any
    tools {
        maven 'maven3.8.6'
        jdk 'jdk'
    }
    stages {
        stage ('Build') {
            steps {
                bat 'mvn -Dmaven.test.failure.ignore=true install' 
            }
            post {
                success {
                    junit 'target/surefire-reports/**/*.xml' 
                }
            }
        }
        stage('Sonarqube') {
            environment {
                scannerHome = tool 'sonarqube'
            }
            steps {
                withSonarQubeEnv('sonarqube') {
                    bat '${scannerHome}/bin/sonar-scanner.bat -D sonar.projectKey=java-maven-junit-helloworld'
                }
            }
        }
        
    }
}
